/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package experiment8_pitest;

/**
 * @Title: APP
 * @Package: experiment8_pitest
 * @Descripate: 实验八，Gradle部署工具集成pitest插件
 * @author: yizhaosan
 */

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
